# M.AKIMOTO
# 2025/05/26
# Makefile for octadiskhistymg

CC = gcc
CFLAGS = -O2 -Wall -std=c99
TARGET = octadiskhistymg

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	rm -f $(TARGET)

